name: Test with Docker Compose

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary
  pull_request:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: flask_app
        ports:
          - 5432:5432

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Start Services
        run: docker-compose -f docker-compose.yml up --build -d

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to be ready..."
          sleep 20  # Adjust the sleep time as necessary

      - name: Run Tests
        run: docker-compose -f docker-compose.yml run app pytest

      - name: Stop Services
        run: docker-compose -f docker-compose.yml down
