name: Test with Docker Compose

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary
  pull_request:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: flask_app
        ports:
          - 5432:5432

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker build -t myapp .

      - name: Start Services
        run: |
          docker run -d --name db -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=secret -e POSTGRES_DB=flask_app -p 5432:5432 postgres:13
          docker run -d --name redis -p 6379:6379 redis:alpine
          echo "Waiting for services to be ready..."
          sleep 20  # Adjust the sleep time as necessary

      - name: Run Tests
        run: |
          docker run --network host myapp pytest

      - name: Stop Services
        run: |
          docker stop db redis
          docker rm db redis
